version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  pkg-build:
    # Preserve same environement to restore cache
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Cached build dependencies
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - v1-deps-{{ .Branch }}
            - v1-deps-

      - run:
          name: Package installation
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}

  pkg-test:
    # Preserve same environement to restore cache
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Cached test dependencies
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum ".circleci/requirements.txt" }}
            - v1-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - v1-deps-{{ .Branch }}
            - v1-deps-

      - run:
          name: CI dependencies installation
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r .circleci/requirements.txt

      - save_cache:
          when: always
          paths:
            - "venv"
          key: v1-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum ".circleci/requirements.txt" }}

      - run:
          name: Package unit tests
          command: |
            . venv/bin/activate
            coverage run -m unittest discover test/
            coverage xml

      - codecov/upload:
          file: coverage.xml
          flags: unittests

  pkg-style:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Cached CI dependencies
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum ".circleci/requirements.txt" }}
            - v1-deps-{{ .Branch }}
            - v1-deps-
      - run:
          name: CI dependencies installation
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r .circleci/requirements.txt
      - save_cache:
          when: always
          paths:
            - "venv"
          key: v1-deps-{{ .Branch }}-{{ checksum ".circleci/requirements.txt" }}

      - run:
          name: Flake8
          command: |
            python3 -m venv venv
            . venv/bin/activate
            flake8 ./

workflows:
  version: 2.1
  build:
    jobs:
      - pkg-build
      - pkg-test:
          requires:
            - pkg-build
      - pkg-style:
          requires:
            - pkg-build
